package com.example.proyecto_final.learning.content

import com.example.proyecto_final.learning.QuizQuestion

object ModuleQuizzes {

    fun allQuizzes(): List<QuizQuestion> =
        module1Quiz() + module2Quiz() + module3Quiz() +
            module4Quiz() + module5Quiz() + module6Quiz()

    fun module1Quiz() = listOf(
        QuizQuestion(1001, 1, "¿Cuál es la longitud mínima recomendada para una contraseña segura?",
            listOf("4 caracteres", "8 caracteres", "12 caracteres", "6 caracteres"), 2,
            "Se recomienda al menos 12 caracteres con combinación de tipos."),
        QuizQuestion(1002, 1, "¿Qué es el credential stuffing?",
            listOf("Crear contraseñas nuevas", "Usar credenciales filtradas en otros sitios", "Guardar contraseñas", "Cambiar contraseñas"), 1,
            "Los atacantes usan credenciales robadas de un sitio para acceder a otros."),
        QuizQuestion(1003, 1, "¿Qué método de 2FA es más seguro?",
            listOf("SMS", "App autenticadora", "Correo electrónico", "Preguntas de seguridad"), 1,
            "Las apps autenticadoras son más seguras que SMS ante SIM swapping."),
        QuizQuestion(1004, 1, "¿Una empresa legítima te pedirá tu contraseña por teléfono?",
            listOf("Sí, siempre", "Solo en emergencias", "Nunca", "Solo por SMS"), 2,
            "Las empresas legítimas nunca solicitan contraseñas por ningún canal."),
        QuizQuestion(1005, 1, "¿Qué es una passphrase?",
            listOf("Una contraseña de un solo carácter", "Varias palabras combinadas con símbolos", "Una contraseña numérica", "Un PIN de 4 dígitos"), 1,
            "Las passphrases combinan palabras para ser memorables y seguras."),
        QuizQuestion(1006, 1, "¿Cuándo debes cambiar tu contraseña?",
            listOf("Cada semana siempre", "Ante filtraciones o accesos sospechosos", "Nunca", "Solo si la olvidas"), 1,
            "Cambia contraseñas ante incidentes de seguridad, no necesariamente por calendario."),
        QuizQuestion(1007, 1, "¿Para qué sirve un gestor de contraseñas?",
            listOf("Recordar una contraseña para todo", "Generar y almacenar contraseñas únicas", "Compartir contraseñas", "Hackear cuentas"), 1,
            "Los gestores generan contraseñas únicas y las almacenan cifradas."),
        QuizQuestion(1008, 1, "¿Qué porcentaje de ataques bloquea la 2FA según Google?",
            listOf("50%", "75%", "99.9%", "10%"), 2,
            "Google reportó que 2FA bloquea el 99.9% de ataques automatizados."),
        QuizQuestion(1009, 1, "¿Es seguro escribir contraseñas en notas del teléfono?",
            listOf("Sí, siempre", "Solo contraseñas débiles", "No, es un riesgo de seguridad", "Solo en Android"), 2,
            "Las notas sin cifrar exponen tus contraseñas si el dispositivo es comprometido."),
        QuizQuestion(1010, 1, "¿Qué contraseña es más segura?",
            listOf("password123", "12345678", "K9#mR\$vL2@pX7", "qwerty"), 2,
            "Contraseñas largas con mayúsculas, minúsculas, números y símbolos son más seguras.")
    )

    fun module2Quiz() = listOf(
        QuizQuestion(2001, 2, "¿Qué es el phishing?",
            listOf("Un tipo de malware", "Engaño para robar información", "Un protocolo de red", "Un antivirus"), 1,
            "El phishing engaña a las víctimas para robar información o dinero."),
        QuizQuestion(2002, 2, "¿Cómo verificar un enlace sospechoso?",
            listOf("Hacer clic directamente", "Pasar el cursor para ver la URL real", "Reenviarlo a amigos", "Ignorarlo"), 1,
            "Inspeccionar la URL real antes de hacer clic es fundamental."),
        QuizQuestion(2003, 2, "¿Qué es el smishing?",
            listOf("Phishing por correo", "Phishing por SMS", "Phishing por teléfono", "Phishing en redes"), 1,
            "Smishing es phishing realizado mediante mensajes de texto."),
        QuizQuestion(2004, 2, "¿Debes compartir códigos OTP con alguien que te llama?",
            listOf("Sí, si dice ser del banco", "Solo si es urgente", "Nunca", "Solo por WhatsApp"), 2,
            "Los códigos OTP son solo para ti; quien los pide es un estafador."),
        QuizQuestion(2005, 2, "¿Qué señal indica un correo de phishing?",
            listOf("Saludo personalizado", "Urgencia artificial", "Logo de la empresa", "Firma del remitente"), 1,
            "La urgencia artificial es una táctica común de phishing."),
        QuizQuestion(2006, 2, "¿HTTPS en un sitio de phishing garantiza seguridad?",
            listOf("Sí, totalmente", "No, solo cifra la conexión", "Solo en móviles", "Solo en bancos"), 1,
            "HTTPS cifra pero no valida la legitimidad del sitio."),
        QuizQuestion(2007, 2, "¿Qué hacer si recibes un correo de phishing?",
            listOf("Responder pidiendo pruebas", "Reportarlo como spam/phishing", "Hacer clic para verificar", "Reenviarlo"), 1,
            "Reporta correos de phishing para protegerte y proteger a otros."),
        QuizQuestion(2008, 2, "¿Qué es el spear phishing?",
            listOf("Phishing masivo", "Phishing personalizado y dirigido", "Phishing por teléfono", "Phishing en juegos"), 1,
            "Spear phishing personaliza ataques para víctimas específicas."),
        QuizQuestion(2009, 2, "¿Un dominio 'paypa1.com' es legítimo?",
            listOf("Sí", "No, es un dominio falso", "Solo en EE.UU.", "Depende del país"), 1,
            "Dominios con caracteres similares imitan sitios legítimos."),
        QuizQuestion(2010, 2, "¿Qué protege contra phishing además del conocimiento?",
            listOf("Solo antivirus", "Actualizaciones y filtros anti-phishing", "Usar HTTP", "Desactivar el correo"), 1,
            "Actualizaciones y filtros complementan la educación del usuario.")
    )

    fun module3Quiz() = listOf(
        QuizQuestion(3001, 3, "¿Cómo acceder a sitios bancarios de forma segura?",
            listOf("Por enlaces en correos", "Escribiendo la URL o usando marcadores", "Por resultados de búsqueda", "Por redes sociales"), 1,
            "Accede directamente o por marcadores para evitar sitios falsos."),
        QuizQuestion(3002, 3, "¿Qué indica HTTPS?",
            listOf("Que el sitio es legítimo", "Que la conexión está cifrada", "Que es gratuito", "Que no tiene virus"), 1,
            "HTTPS cifra la comunicación pero no garantiza legitimidad."),
        QuizQuestion(3003, 3, "¿De dónde descargar software de forma segura?",
            listOf("Sitios de cracks", "Sitios oficiales del desarrollador", "Cualquier enlace", "Foros anónimos"), 1,
            "Descarga solo de fuentes oficiales para evitar malware."),
        QuizQuestion(3004, 3, "¿Por qué actualizar el navegador?",
            listOf("Para nuevas funciones solamente", "Para corregir vulnerabilidades de seguridad", "No es necesario", "Solo en computadoras"), 1,
            "Las actualizaciones corrigen vulnerabilidades explotables."),
        QuizQuestion(3005, 3, "¿Qué extensión de archivo es potencialmente peligrosa?",
            listOf(".txt", ".jpg", ".exe", ".mp3"), 2,
            "Los archivos .exe pueden ejecutar código malicioso."),
        QuizQuestion(3006, 3, "¿Qué es un drive-by download?",
            listOf("Descarga voluntaria", "Infección al visitar una página maliciosa", "Descarga por USB", "Actualización automática"), 1,
            "Drive-by downloads infectan al simplemente visitar sitios maliciosos."),
        QuizQuestion(3007, 3, "¿Debes compartir todos los datos que pide un formulario?",
            listOf("Sí, siempre", "Solo los datos mínimos necesarios", "Nunca ninguno", "Solo en sitios .com"), 1,
            "Proporciona solo la información estrictamente necesaria."),
        QuizQuestion(3008, 3, "¿Qué hacer ante advertencia de certificado del navegador?",
            listOf("Continuar de todos modos", "No ingresar datos y salir", "Ignorarla", "Desactivar HTTPS"), 1,
            "Las advertencias de certificado indican posibles riesgos de seguridad."),
        QuizQuestion(3009, 3, "¿Las extensiones del navegador pueden ser peligrosas?",
            listOf("No, nunca", "Sí, si son maliciosas", "Solo en Firefox", "Solo las gratuitas"), 1,
            "Extensiones maliciosas pueden robar datos y modificar navegación."),
        QuizQuestion(3010, 3, "¿En Wi-Fi público, qué precaución tomar?",
            listOf("Acceder a todo sin precaución", "Evitar datos sensibles o usar VPN", "Compartir la contraseña", "Desactivar el firewall"), 1,
            "En Wi-Fi público usa VPN o evita actividades sensibles.")
    )

    fun module4Quiz() = listOf(
        QuizQuestion(4001, 4, "¿Qué es la regla 3-2-1 de backups?",
            listOf("3 contraseñas, 2 emails, 1 teléfono", "3 copias, 2 medios, 1 offsite", "3 dispositivos, 2 redes, 1 router", "3 apps, 2 cuentas, 1 backup"), 1,
            "3 copias en 2 medios diferentes con 1 copia fuera del sitio."),
        QuizQuestion(4002, 4, "¿Por qué revisar permisos de apps?",
            listOf("Para ahorrar batería", "Para limitar acceso innecesario a datos", "No es necesario", "Solo en iPhone"), 1,
            "Permisos excesivos exponen tu información innecesariamente."),
        QuizQuestion(4003, 4, "¿Qué hacer si pierdes tu teléfono?",
            listOf("Esperar a que aparezca", "Usar buscar mi dispositivo y borrado remoto", "Comprar uno nuevo sin más", "Publicar en redes sociales"), 1,
            "El borrado remoto protege tus datos en dispositivos perdidos."),
        QuizQuestion(4004, 4, "¿Qué datos son más valiosos para atacantes?",
            listOf("Solo contraseñas", "Perfiles completos de identidad", "Solo fotos", "Solo contactos"), 1,
            "Los perfiles completos permiten robo de identidad y fraude."),
        QuizQuestion(4005, 4, "¿Una app de linterna necesita acceso a contactos?",
            listOf("Sí, siempre", "No, es un permiso sospechoso", "Solo de noche", "Solo en Android"), 1,
            "Apps que piden permisos innecesarios son sospechosas."),
        QuizQuestion(4006, 4, "¿Con qué frecuencia revisar configuración de privacidad?",
            listOf("Nunca", "Cada 3 meses aproximadamente", "Cada 10 años", "Solo al instalar"), 1,
            "Revisar privacidad regularmente mantiene el control de tus datos."),
        QuizQuestion(4007, 4, "¿Por qué cifrar el dispositivo?",
            listOf("Para más espacio", "Para proteger datos si es robado", "Para mejor batería", "No es necesario"), 1,
            "El cifrado protege datos ante acceso físico no autorizado."),
        QuizQuestion(4008, 4, "¿Qué es el robo de identidad?",
            listOf("Robar un dispositivo", "Usar datos ajenos para fraude", "Hackear una red", "Copiar archivos"), 1,
            "El robo de identidad usa datos personales para cometer fraudes."),
        QuizQuestion(4009, 4, "¿Los backups deben probarse?",
            listOf("No, confiar en ellos", "Sí, verificar que se pueden restaurar", "Solo los de nube", "Nunca"), 1,
            "Un backup no verificado puede fallar cuando lo necesites."),
        QuizQuestion(4010, 4, "¿PIN de bloqueo seguro?",
            listOf("1234", "0000", "Al menos 6 dígitos aleatorios", "Tu fecha de nacimiento"), 2,
            "Usa PINs largos y aleatorios, no fechas ni secuencias obvias.")
    )

    fun module5Quiz() = listOf(
        QuizQuestion(5001, 5, "¿Qué protocolo Wi-Fi es más seguro?",
            listOf("WEP", "WPA original", "WPA2-AES o WPA3", "Sin contraseña"), 2,
            "WPA2-AES es el mínimo; WPA3 es el más seguro actualmente."),
        QuizQuestion(5002, 5, "¿Por qué cambiar credenciales del router?",
            listOf("Para más velocidad", "Las predeterminadas son públicamente conocidas", "No es necesario", "Solo en oficinas"), 1,
            "Credenciales por defecto están en listas públicas de atacantes."),
        QuizQuestion(5003, 5, "¿Qué es WPS y por qué desactivarlo?",
            listOf("Mejora la velocidad", "Tiene vulnerabilidades de seguridad", "Es obligatorio", "Protege la red"), 1,
            "WPS tiene vulnerabilidades que permiten ataques de fuerza bruta."),
        QuizQuestion(5004, 5, "¿Qué hacer si ves dispositivos desconocidos en tu Wi-Fi?",
            listOf("Ignorarlos", "Cambiar contraseña y bloquearlos", "Compartir más la contraseña", "Apagar el router"), 1,
            "Dispositivos desconocidos indican acceso no autorizado."),
        QuizQuestion(5005, 5, "¿Por qué actualizar firmware del router?",
            listOf("Para más Wi-Fi", "Para corregir vulnerabilidades", "No es necesario", "Solo una vez"), 1,
            "El firmware desactualizado puede tener vulnerabilidades explotables."),
        QuizQuestion(5006, 5, "¿Qué es una red de invitados?",
            listOf("Wi-Fi sin contraseña", "Red separada para visitantes", "Red solo para IoT", "Red de empresa"), 1,
            "Las redes de invitados aíslan visitantes de tus dispositivos principales."),
        QuizQuestion(5007, 5, "¿WEP es seguro?",
            listOf("Sí, muy seguro", "No, se crackea fácilmente", "Solo en redes pequeñas", "Mejor que WPA3"), 1,
            "WEP fue crackeado y no debe usarse nunca."),
        QuizQuestion(5008, 5, "¿Qué es DNS hijacking?",
            listOf("Mejorar DNS", "Redirigir tráfico a sitios maliciosos", "Acelerar internet", "Cifrar DNS"), 1,
            "Un router comprometido puede redirigir tu tráfico a sitios falsos."),
        QuizQuestion(5009, 5, "¿Por qué segmentar dispositivos IoT?",
            listOf("Para más velocidad", "Tienen seguridad débil y aíslan riesgos", "Es obligatorio", "No tiene sentido"), 1,
            "Los IoT frecuentemente tienen seguridad débil y deben aislarse."),
        QuizQuestion(5010, 5, "¿Con qué frecuencia revisar dispositivos conectados?",
            listOf("Nunca", "Mensualmente", "Cada 10 años", "Solo al instalar"), 1,
            "Revisar mensualmente detecta accesos no autorizados a tiempo.")
    )

    fun module6Quiz() = listOf(
        QuizQuestion(6001, 6, "¿Qué es la ingeniería social?",
            listOf("Hackear sistemas", "Manipular personas para obtener información", "Diseñar redes", "Programar software"), 1,
            "La ingeniería social manipula personas, no sistemas técnicos."),
        QuizQuestion(6002, 6, "¿Qué emoción explotan los atacantes?",
            listOf("Solo miedo", "Urgencia, miedo, curiosidad y codicia", "Solo alegría", "Ninguna"), 1,
            "Múltiples emociones son explotadas para manipular víctimas."),
        QuizQuestion(6003, 6, "¿Cómo verificar identidad de quien llama?",
            listOf("Usar el número que te dieron", "Llamar al número oficial de la empresa", "Enviar un WhatsApp", "Confiar en la voz"), 1,
            "Siempre verifica por un canal independiente y oficial."),
        QuizQuestion(6004, 6, "¿Qué es el vishing?",
            listOf("Phishing visual", "Ingeniería social por voz/teléfono", "Phishing en video", "Estafa por correo"), 1,
            "Vishing es ingeniería social realizada por teléfono."),
        QuizQuestion(6005, 6, "¿Qué hacer ante presión para actuar rápido?",
            listOf("Actuar inmediatamente", "Detenerse y verificar", "Enviar dinero", "Dar información"), 1,
            "La urgencia artificial es señal de alerta; detente y verifica."),
        QuizQuestion(6006, 6, "¿Qué es el CEO fraud?",
            listOf("Fraude de tarjetas", "Suplantar ejecutivos para transferencias", "Robo de identidad", "Phishing masivo"), 1,
            "CEO fraud impersona ejecutivos para solicitar transferencias urgentes."),
        QuizQuestion(6007, 6, "¿Publicar planes de viaje en tiempo real es seguro?",
            listOf("Sí, siempre", "No, alerta a delincuentes", "Solo en privado", "Solo en Instagram"), 1,
            "Publicar viajes en tiempo real indica que tu casa está vacía."),
        QuizQuestion(6008, 6, "¿Qué es un deepfake?",
            listOf("Un antivirus", "Contenido falso generado por IA", "Un firewall", "Un protocolo"), 1,
            "Los deepfakes falsifican imagen y voz con inteligencia artificial."),
        QuizQuestion(6009, 6, "¿Debes reportar intentos de estafa?",
            listOf("No, es inútil", "Sí, protege a otros y ayuda a autoridades", "Solo si perdiste dinero", "Solo en redes sociales"), 1,
            "Reportar ayuda a combatir el cibercrimen y proteger a otros."),
        QuizQuestion(6010, 6, "¿Cuánto esperar antes de actuar en solicitudes inusuales?",
            listOf("Actuar ya", "Al menos 24 horas para verificar", "Un minuto", "Un año"), 1,
            "Esperar permite verificar sin la presión del momento.")
    )
}
